# Generated by Django 6.0.6 on 2026-07-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_фото_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='Фото',
        ),
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images/', verbose_name='Фото'),
        ),
    ]
